local icons = require("core.icons")
local kind = icons.kind

require("nvim-navic").setup({
    icons = {
        Array = kind.Array .. " ",
        Boolean = kind.Boolean,
        Class = kind.Class .. " ",
        Color = kind.Color .. " ",
        Constant = kind.Constant .. " ",
        Constructor = kind.Constructor .. " ",
        Enum = kind.Enum .. " ",
        EnumMember = kind.EnumMember .. " ",
        Event = kind.Event .. " ",
        Field = kind.Field .. " ",
        File = kind.File .. " ",
        Folder = kind.Folder .. " ",
        Function = kind.Function .. " ",
        Interface = kind.Interface .. " ",
        Key = kind.Key .. " ",
        Keyword = kind.Keyword .. " ",
        Method = kind.Method .. " ",
        Module = kind.Module .. " ",
        Namespace = kind.Namespace .. " ",
        Null = kind.Null .. " ",
        Number = kind.Number .. " ",
        Object = kind.Object .. " ",
        Operator = kind.Operator .. " ",
        Package = kind.Package .. " ",
        Property = kind.Property .. " ",
        Reference = kind.Reference .. " ",
        Snippet = kind.Snippet .. " ",
        String = kind.String .. " ",
        Struct = kind.Struct .. " ",
        Text = kind.Text .. " ",
        TypeParameter = kind.TypeParameter .. " ",
        Unit = kind.Unit .. " ",
        Value = kind.Value .. " ",
        Variable = kind.Variable .. " ",
    },
    highlight = true,
    separator = " " .. icons.ui.ChevronRight .. " ",
    depth_limit = 0,
    depth_limit_indicator = "..",
})
